name: scheduleapp
description: A new Flutter project.

 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

 
dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  get_it: ^7.2.0
  dotted_line: ^3.1.0
  flutter_bloc: ^8.0.1
  date_format: ^2.0.6
  dio: ^4.0.6
  intl: ^0.17.0
 
  flutter_lints: ^1.0.0

 
flutter:

 
  uses-material-design: true

  assets:
    - assets/images/
 

 
  fonts:
    - family: Euclid Circular B
      fonts:
        - asset: assets/fonts/Euclid-Regular.ttf
          weight: 400
        - asset: assets/fonts/Euclid-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-SemiBold.ttf
          weight: 600
  
   
